### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by binarization** [binarization/mall-wechat-mp#1]
> Task List

- [ ] 搭建静态页面
  - [x] 焦点图和分割栏 ................................ [**learn CSS**:_[ position useage](http://zh.learnlayout.com/position.html)_]
  - [x] 商品栏（Hard Code 实现）
  - [x] 商品栏（循环实现）
- [ ] 配置服务器和搭建数据库
  - [ ] 服务器配置
  - [ ] 图片上传和数据库初始化
- [ ] 设计 API 接口
  - [ ] 路由
  - [ ] 控制器
- [ ] API 数据请求和呈现
  - [ ] API 请求数据
- [ ] 搭建商品详情页面
  - [ ] 静态页面构建
  - [ ] API 请求完成数据更新

**Comment by binarization** [comment]
### 搭建商品详情页面

- [ ] 添加空白的商品详情页面
- [ ] 填充虚拟数据
- [ ] 完成商品卡片的结构和样式
- [ ] 完成服务和评价的结构和样式
- [ ] 完成操作区域的结构和样式

Overview
